func.go, native.go, runtime.go, runtime_test.go, value.go, vm.go
This change also allows setting an upper limit to the number of stack frames used when formatting an error's stack trace.
=> REALMC-7470 format stack traces for native errors properly

builtin_regexp.go, regexp.go, regexp_test.go
- capture the lookbehind expression within the results
- properly support the option to specify a different prototype with Reflect.construct
=> REALMC-7500 fix regexp lookbehind results and constructor

builtin_array.go, object.go, runtime.go, runtime_test.go
If an array ever contained itself in a Javascript function, it would end up creating a Stack Overflow panic when being executed. This was because of a loop found in the array's `toString()` methods where the method was iterating through the array and calling each element's `toString()` method. 
I added a variable to the `Runtime` object that would keep track of the objects seen while iterating through an array. If an object has been seen before, the method will append `[<Circular Value>]` to the string instead of going into a loop.
=> REALMC-7473: Add support for cyclical arrays

compiler_expr.go
I dug around and found that when the an integer arg comes in from js, it will always become a valueInt. this will fix that case and properly delineate between
=> REALMC-7948: support int64 type 

builtin_json.go
This will output the same as before for ascii strings and handle the hex string cases that we just introduced in baas
=> REALMC-8476: use go json marshal for ascii strings

string_ascii.go
This was a nightmare to discover. Here is the issue:
```js
const db = context.services.get('database').db(context.values.get('DB_NAME'));
const { insertedId } = await db.collection('test').insertOne({ name: 'Übersicht' });
const loadedModel = await db.collection('test').findOne({ _id: insertedId });
 
// These two are different and the second one prints "Ãbersicht"
console.log(new Buffer('Übersicht').toString('utf-8'));
console.log(new Buffer(loadedModel.name).toString('utf-8'))
```
=> REALMC-9481: fix charCodeAt not working as expected with special char

limiter.go, runtime.go, vm.go
I've been mostly analyzing the CPU usage with the following function, which came up from this [help ticket](https://jira.mongodb.org/browse/HELP-27429).
```
exports = function(arg){
const bcrypt = require("bcryptjs");
return bcrypt.hashSync('bacon', 8);
}
```
With the following changes, we now use less than 1/10 of the CPU time used in master, which means that we can bump up the rate limit in baas.
=> REALMC-10239 reduce CPU usage while rate limiting

value.go
This turned out to be a simpler and saner change to satisfy goja test suite and `baas`. Otherwise I'd have to change many of our tests to expect an `int64`.
=> REALMC-11731: Fix return type for valueInt

runtime.go, typedarrays.go
_Note: I've added a simple commit for now to get this PR up and running._ 
There are a few approaches we can take here to support this conversion (please let me know if there's a better solution that I've missed). Wanted to get this conversation going and get everyone's thoughts! Some background on why we need this: 
In [`lib_http_parser.go`](https://github.com/10gen/baas/blob/master/function/execution/vm/lib_http_parser.go#L394), we call the [`parserOnBody`](https://github.com/10gen/baas/blob/master/function/execution/common/nodejs_standard_libraries/_http_common.js#L106) function in `_http_common.js`. We end up converting the passed in [`body []byte`](https://github.com/10gen/baas/blob/master/function/execution/vm/lib_http_parser.go#L394) as a …
=> REALMC-11774: support conversion to JS Uint8Array from a Go byte slice

memory_test.go, runtime.go, runtime_test.go, vm.go
I am fine not merging this PR, but wanted to put out the option if we/users would want visibility into errors while we properly implement Error.captureStackTrace()
This solution is a quick stopgap until [REALMC-10739](https://jira.mongodb.org/browse/REALMC-10739) is implemented. Instead of setting the stack property on the Error and returning a string representation, we just return an empty string. This allows users who are running into their errors being masked by captureStackTrace not being defined can proceed (e.g. the flaky sendgrid test is failing but we cannot see the actual error because we get back `captureStackTrace is not a function`).
The first commit allows us to write a Realm function that calls Error.captureStackTrace explicitly. The second commit is a stopgap to work with …
=> REALMC-12488: prevent errors being masked due to lack of captureStackTrace support

memory_test.go, runtime.go
removing this means we are fully reliant on checking if captureStackTrace is invoked, and if so returning an empty string regardless if the callee is actually an error, but this keeps us more aligned with actual js Error object
=> REALMC-12488 remove explicit setting of captureStackTrace on Error creation

added_values.go, added_values_test.go, value.go, value_test.go, vm_test.go
fixes issue where `[0].includes(0.0)` and `[0.0].includes(0)` return false. Array.includes calls SameAs on the values and not equals so the changes are only needed in SameAs. 
Note: The check is only for Float, Int, and Int64 types. While Equals will return true if the Int is being compared to and identical string or boolean representation, I don't believe we should add that to `SameAs` since those types are different and non-number types
=> BAAS-11318 make int and int64 SameAs return true for equivalent floats

array.go, memory_test.go
A customer had a very large array dense with data. When we calculate memory usage of a large array we keep computing until we reach the end of the array.
This would NOT take into account that we could reach the memory limit way before iterating through the whole array. This caused the function to eventually time out and our host memory to spike (and eventually die) since we would continue going with our computation beyond the memory limit.
This PR only demonstrate 1 of a few possible paths forward:
1. Surfacing memory usage at intervals to the poller so that we can interrupt function execution without the need to go through the entire array
2. Check memory usage in goja so that we can stop iterating once we reach the limit
3. Provide an estimate based on samples of values from the array
I …
=> BAAS-17382: address mem usage issue for large arrays

builtin_number.go, builtin_number_test.go
[BAAS-18471](https://jira.mongodb.org/browse/BAAS-18471)
The main issue is that the dependency is-odd is setting a value calling math_abs() which returns a float value. The below is the detailed explanation:
1. The is-odd package calls math.abs() which converts string and negative numbers to the positive number.
2. The math.abs() has a native function implementation in goja which always returns valueFloat.
3. Then the isSafeInteger() is called from the is-odd package which leads to the goja problem with the valueFloat
Summary of the change:
Made a change to isSafeInteger to handle a valueFloat since isInteger() already has a case to handle floats ([code link](https://github.com/mongodb-forks/goja/blob/realm/builtin_number.go#L188)). We can add a check if the value coming in isSafeInteger …
=> BAAS-18471: Add float integers support in the isSafeInteger native function

func.go, runtime.go, vm.go
The issue has been present since at least May(it's a bit difficult going further back due to breaking baas changes). This might be caused by reusing the vm in an event loop and can make a ticket if we want to experiment with that route
=> BAAS-17702 add mutex to vm funcName to prevent data race

added_values.go, added_values_test.go, builtin_array.go, compiler.go, compiler_expr.go, compiler_stmt.go, compiler_test.go, value.go, value_test.go, vm.go, vm_test.go
The first commit brings in an additional change from goja the second restores the functionality of SameAs that we had to chance for this `[0.0].includes(0)` to return `true`.
* Generally a `SameAs` is expected to return `false` when you compare a float to an int/int64. Fort that reason I removed the float assertion.
* Some tests were verifying the behavior of `SameAs` that we introduced to support the `includes` behavior. Those have been updated to use `StrictEquals`.
* In order to maintain the correct functionality of `includes` we now use `StrictEquals` to compare items.
* Test cases where we passed `-0` from go have been removed since they are treated exactly the same as passing `0`
I tested this with some relevant use cases and all seemed good, I have a patch in progress …
=> BAAS-19768: Add constant folding to variable assignments, fix float to int comparisons

builtin_reflect.go
I think it would be nice if it logged the actual value name like Node does but I won't make that change and stay consistent for now.
=> BAAS-19940: return type error when value is not a constructor

array.go, mem_context.go, memory_test.go, object.go
I tested this in `baas` with a function like
```
exports = async function(arg){
i = 0;
testObj = {};
while (true) {
testObj[i] = "a";
i++;
}
return "hello";
};
```
the before and after was quite a big difference, with this change we threw an error much faster!
This might not address nested objects, but the sampling will mitigate that. We would probably need a follow up to this change to better take that into account.
=> BAAS-21844: estimate mem usage for large objects

vm.go
https://jira.mongodb.org/browse/BAAS-23710
current
```
goja (BAAS-23710_reduceGetFuncNameCallsInSaveCtx)$ go test -bench=^BenchmarkFib$ -run=^$
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkFib-10                1        4053097750 ns/op
```
new
```
goja (BAAS-23710_reduceGetFuncNameCallsInSaveCtx)$ go test -bench=^BenchmarkFib$ -run=^$
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkFib-10                1        3649985291 ns/op
```
BenchmarkFib saw roughly a 9.9% performance improvement
=> BAAS-23710: Reduce getFuncName calls in saveCtx

vm.go
https://jira.mongodb.org/browse/BAAS-23655
This rolls back this [commit](https://github.com/Calvinnix/goja/commit/f95411d186f2183429261010a860c604371ac6a7) from the maintainer that was fixing a bug where Runtime.interrupt was never called.
This change would fail `TestRunLoopPreempt` but we haven't ran that test since it was commented out [here](https://github.com/Calvinnix/goja/commit/c84a6965a8e80876c246809bd7e747004402e761)
I'm making an assumption that our custom interrupt logic resolves the need for calling runtime.Gosched periodically. If we see issues, worst case scenario we could add runtime.Gosched inside of waitOneTick.
current
```
goja (realm)$ go test -bench=^BenchmarkEmpty -benchtime 10000000x
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkEmptyLoop-10 …
```
=> BAAS-23655: Remove internal goja tick counter

limiter.go, runtime.go, vm.go, vm_test.go
https://jira.mongodb.org/browse/BAAS-23656
Benchmark results:
current
```
goja (BAAS-23656_removeSelfLimiterNilCheck)$ go test -bench=BenchmarkEmptyLoop$ -run=$ -benchtime 1000000x
--
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkEmptyLoop-10            1000000              6143 ns/op
PASS
ok      github.com/dop251/goja  6.537s
```
new
```
goja (BAAS-23656_removeSelfLimiterNilCheck)$ go test -bench=BenchmarkEmptyLoop$ -run=$ -benchtime 1000000x
--
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkEmptyLoop-10            1000000              6047 ns/op
PASS
ok      github.com/dop251/goja  6.237s
```
Roughly a 1.5% improvement
Note: there are still a few additional goja tests that I'll need to update to ensure limiter isn't nil, but wanted to gather opinions …
=> BAAS-23656: Remove limiter nil check in waitOneTick method

builtin_object.go
```
goja (BAAS-23701)$ go test -bench=^BenchmarkObjectproto -run=^$ -benchmem
goos: darwin
goarch: arm64
pkg: github.com/dop251/goja
BenchmarkObjectproto_toString-10                19064584                62.89 ns/op           40 B/op          2 allocs/op
BenchmarkObjectprotoImproved_toString-10        81820740                14.77 ns/op            0 B/op          0 allocs/op
PASS
```
```
func BenchmarkObjectproto_toString(b *testing.B) {
clsName := "someclass"
for i := 0; i < b.N; i++ {
_ = func(s string) string {
return fmt.Sprintf("[object %s]", clsName)
}(clsName)
}
}
func BenchmarkObjectprotoImproved_toString(b *testing.B) {
clsName := "someclass"
for i := 0; i < b.N; i++ {
_ = func(s string) string {
return "[object " + clsName + "]"
}(clsName)
}
}
```
=> BAAS-23701: reduce allocations in objectproto_toString by avoiding Sprintf usage

limiter.go, limiter_test.go
This change just means we can't override the limiter with a nil limiter.
This works now because we are defaulting the limiter [here](https://github.com/Calvinnix/goja/blob/9b379545217111b76b9286649a58ac61685ecd31/runtime.go#L508).
=> BAAS-24170: Prevent setting rate limiter to nil

array.go, array_sparse_test.go, array_test.go, builtin_map_test.go, date_test.go, memory_test.go, object.go, object_dynamic_test.go, object_gomap.go, object_gomap_test.go, object_goslice_test.go, object_test.go, proxy_test.go, runtime_test.go, string.go, string_ascii.go, string_ascii_test.go, string_imported.go, string_imported_test.go, string_test.go, string_unicode.go, string_unicode_test.go, typedarrays_test.go, value.go, value_test.go, vm_test.go
Doing this so that the memory usage is now correct and the new memory usage has the only difference of accounting for objectGoSlice and objectGoMapSimple. This will help us differentiate the contribution and diff of these new memory changes.
I expect moving forward for the process to be similar to this, once the memory changes are in production and we are good, we can promote them in goja as well so that any new memory change can be tracked independently.
Estimates and early exit for objectGoSlice and objectGoMapSimple are part of a follow-up ticket.
=> BAAS-23857: apply new mem usage everyhere but objectGoSlice and objectGoMapSimple

builtin_string.go, string_ascii.go, tc39_test.go
(cherry picked from commit 6df49a26cb0c465a051b7773f6b27b81685d7d63)
=> BAAS-24673: Implement String.prototype.replaceAll

array_test.go, mem_context.go
- Achieved by modifying the value type of visitTracker from bool to struct{}
=> BAAS-24725: Optimize visitTracker struct
